### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by thexande** [airbnb/buck#27]
<img width="412" alt="Screen Shot 2020-12-18 at 11 26 28 AM" src="https://user-images.githubusercontent.com/7704414/102647971-e9605f00-4123-11eb-8f14-8e920e1e3298.png">

It seems that this fork has not been kept up to date with the facebook repo. Is there a reason for this? I noticed you all moved to Java 11 in the Buck Sample repo, and I'm wondering if this public facing fork has diverged from your internal implementation. 

Thanks!

--Alex

**Comment by qyang-nj** [comment]
Hi Alex, we don't have other buck fork internally. The buck we are using is the `airbnb-ios` branch in this repo. Since current buck is pretty stable, we just pull `facebook:master` quarterly (but it seems somehow we didn't do it this quarter).

**Comment by thexande** [comment]
Thank you so much for the information.
